PRINT ~TEST~

/*
  OR(2)
!Global("ViconiaRomanceActive","GLOBAL",1)
!IsValidForPartyDialogue("Viconia")
OR(2)
!Global("JaheiraRomanceActive","GLOBAL",1)
!IsValidForPartyDialogue("Jaheira")

  Global("ViconiaRomanceActive","GLOBAL",1)
IsValidForPartyDialogue("Viconia")

  OR(2)
!Global("ViconiaRomanceActive","GLOBAL",1)
!IsValidForPartyDialogue("Viconia")
Global("JaheiraRomanceActive","GLOBAL",1)
IsValidForPartyDialogue("Jaheira")
*/

COPY_EXISTING ~BAERIE.DLG~ ~override~
 DECOMPILE_AND_PATCH BEGIN
  REPLACE_TEXTUALLY ~OR(2) !Global("ViconiaRomanceActive","GLOBAL",1) !IfValidForPartyDialogue("Viconia") OR(2) !Global("JaheiraRomanceActive","GLOBAL",1) !IfValidForPartyDialogue("Jaheira")~ ~Global("AerieRomanceActive","GLOBAL",1)~
  REPLACE_TEXTUALLY ~Global("ViconiaRomanceActive","GLOBAL",1) IfValidForPartyDialogue("Viconia")~ ~!Global("AerieRomanceActive","GLOBAL",1)~
  REPLACE_TEXTUALLY ~OR(2) !Global("ViconiaRomanceActive","GLOBAL",1) !IfValidForPartyDialogue("Viconia") Global("JaheiraRomanceActive","GLOBAL",1) IfValidForPartyDialogue("Jaheira")~ ~!Global("AerieRomanceActive","GLOBAL",1)~
 END